language: scala
scala:
   - 2.10.4
script:
  - sbt -jvm-opts travis/jvmopts.build ++$TRAVIS_SCALA_VERSION clean test
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
notifications:
  email:
    - pbarron@gilt.com
